FROM centos:centos7

RUN yum install -y epel-release
RUN yum install -y nginx
RUN adduser -g 'www' www \
mkdir /var/www \
chown -R www:www /var/www/ \
chown -R www:www /var/lib/nginx
COPY index.html /var/www/
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]




